services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: bento-backend
    ports:
      - '3000:3000'
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
